export const colors = {
  tabBarActiveTintColor: 'black',
  tabBarInactiveTintColor: '#CDCACA',
  borderTopBottomColor: '#CDCACA',
  background: '#F4F4F4',
  buttonColor: '#000000',
  buttonDisabledColor: '#D9D9D9',
  snsButtonTextColor: 'white',
  snsButtonBackground: '#000000',
  inputLineColor: '#CDCACA',
  inputLabelColor: '#828282',
  inputPlaceHolderColor: '#CBCBCB',
  itemBorderBottomColor: '#CDCACA',
  buttonBorderColor: 'rgba(202, 209, 215, 0.8)',
  moreButtonColor: '#BBBBBB',
  bottomSheetItemBorderColor: '#EAEAEA',
  positiveColor: '#007AFF',
  negativeColor: '#FF3B30',
  cardBorderBottomColor: '#CDCACA',
  subTitleColor: '#C2C2C2',
  prayButtonEditBkgColor: '#EBF6FD',
  prayButtonSaveBkgColor: '#EAFFEA',
  prayButtonDeleteBkgColor: '#ffeaed',
  prayButtonEditTextColor: '#198CED',
  prayButtonSaveTextColor: '#43A54D',
  prayButtonDeleteTextColor: 'red',
  prayButtonAlarmBkgColor: 'rgba(158, 0, 255, 0.08)',
  prayButtonAlarmTextColor: '#DB00FF',
  prayButtonCheerTextColor: 'D004FF',
  settingButtonBkgColor: '#F4F4F4',
  settingButtonTextColor: '#828282',

  loadingIconColor: 'gray',
};
