export const colors = {
  tabBarActiveTintColor: 'black',
  tabBarInactiveTintColor: '#CDCACA',
  borderTopBottomColor: '#CDCACA',
  background: '#F4F4F4',
  buttonColor: '#000000',
  snsButtonTextColor: 'white',
  snsButtonBackground: '#000000',
  inputLineColor: '#CDCACA',
  inputLabelColor: '#828282',
  inputPlaceHolderColor: '#CBCBCB',
  itemBorderBottomColor: '#CDCACA',
  buttonBorderColor: 'rgba(202, 209, 215, 0.8)',
  moreButtonColor: '#BBBBBB',
  bottomSheetItemBorderColor: '#EAEAEA',
  positiveColor: '#007AFF',
  negativeColor: '#FF3B30',
};
